### ISSUE TITLE
Dataset Problems

### ISSUE THREAD

**Issue by Auggst** [darthgera123/Appearance-Editing#1]
Thanks for your works. 

I just want to know if you have ideas to public the datasets?

**Comment by darthgera123** [comment]
Hi thanks for the interest. We will upload the data very soon

**Comment by darthgera123** [comment]
Hi @Auggst we have shared the data. all the best for your project

**Comment by Auggst** [comment]
> Hi @Auggst we have shared the data. all the best for your project

Thanks!
